### ISSUE TITLE
Celsius to Farenheit? 

### ISSUE THREAD

**Issue by theadamdisney** [adriaanjelle/JDWS-02#1]
Hi there,

How do you change the weather to your location in the usa and to Fahrenheit?

Thank you! :)

**Comment by adriaanjelle** [comment]
I am so so so sorry for the late reply (I didn't notice the open issue until now), but to do this you have to right-click the skin, hit 'Global settings' and then set the WeatherUnits option to Imperial, so like this: `WeatherUnits=Imperial`.
